### ISSUE TITLE
Google News Decorder not working

### ISSUE THREAD

**Issue by nandhadeva** [SSujitX/google-news-url-decoder#2]
Hi @SSujitX 
https://news.google.com/rss/articles/CBMiqwFBVV95cUxNMTRqdUZpNl9hQldXbGo2YVVLOGFQdkFLYldlMUxUVlNEaElsYjRRODVUMkF3R1RYdWxvT1NoVzdUYS0xSHg3eVdpTjdVODQ5cVJJLWt4dk9vZFBScVp2ZmpzQXZZRy1ncDM5c2tRbXBVVHVrQnpmMGVrQXNkQVItV3h4dVQ1V1BTbjhnM3k2ZUdPdnhVOFk1NmllNTZkdGJTbW9NX0k5U3E2Tkk?oc=5

i can't get original url dube. Google using Different encode on yesterday

**Comment by lordwebbie** [comment]
Wow, just came here after some googleing. I also saw this problem for the first time today and I am not even using this library...

The problem is that the base64 encoded string now seems to decode to something that starts with "AU_" but does not contain the original URL in clear text anymore.

I guess we will have to put a little experimentation work into this. And we cannot be sure whether the "new" string isn't just a hash or something that can't be decoded anymore...

**Comment by fdmsh** [comment]
Same for me, it is not working no more

**Comment by SSujitX** [comment]
#1 Check read me. Updated v2.

**Comment by SSujitX** [comment]
Please check [decode_google_news_url_v2.py](https://github.com/SSujitX/google-news-url-decoder/blob/main/decode_google_news_url_v2.py). Thanks.

**Comment by SSujitX** [comment]
> Thx, Let's collaborate together to find fix overtime... GG constantly chaging...

check invitation.
